GPIOB_BASE GPIO_CRL + constant PB-CRL-R
GPIOB_BASE GPIO_CRH + constant PB-CRH-R
GPIOB_BASE GPIO_IDR + constant PB-IDR-R
GPIOB_BASE GPIO_ODR + constant PB-ODR-R
GPIOB_BASE GPIO_BSRR + constant PB-BSRR-R

: SETUP-PB0-7 
	$9 RCC_APB2ENR_R HBIS!
	AFIO_BASE AFIO_MAPR + DUP @ 
	$7000000 BIC $4000000 OR SWAP ! 
	$22222222 PB-CRL-R ! 
	$FFFF0000 PB-BSRR-R !
;

SETUP-PB0-7

: tpb-ms ( ms -- )
	1024 0 DO 
		I 8 MOD 1 SWAP LSHIFT 
		DUP HEX. CR 
		PB-ODR-R ! 
		dup ms
	LOOP 
	drop
; 

